### PR TITLE
Many Updates since last pull

### PR DESCRIPTION
**Pull request by McSkinnerOG**
Changed Kits a bit.
Added Command Teleports to all Points of Interest/Towns
Added ability to change skins ingame via command.
Added ability to change cosmetics "hats" ingame via command.
Added Return messages for Item SPawning "still WIP"
Added /players & /online to return current online players "Kind of redundant as it shows in the Tablet GUI anyway"
Player position now gets returned with other /stats

### CODE REVIEW

**Comment by Donaut** [comment]
Our script extension class is getting too big. Consider redesign the way we implement Commands!

**Comment by McSkinnerOG** [comment]
Have you made any progress? I will try to reformat soon.

**Comment by Donaut** [comment]
i tried to search alternatives to reflection (static constructor) but it's seems reflection is the only way to go. My plan is that i make an interface and all the chat command class should inherite that.

**Comment by Donaut** [comment]
Ok, I close the pull request. It's because I tried so hard but the game is giving me constant errors.

Old .Net framework version and hard debugging.

**Pull request closed without merging**
